# Length and width dimension of image taken by camera in inches
[image]
dimension = 6
threshold = 150


# Runway dimensions in feet
[runway]
length = 40
width = 32
# Valid unit values are "inches" and "feet"
units = "inches"
# Percentage of runway with friction too low
percent = 0.05
